package com.fajarachmad.tutorial.domain;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_NAME
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWORD
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.FLAG_ACTIVE
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    private boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ID
     *
     * @return the value of USER.ID
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ID
     *
     * @param id the value for USER.ID
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_NAME
     *
     * @return the value of USER.USER_NAME
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_NAME
     *
     * @param userName the value for USER.USER_NAME
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PASSWORD
     *
     * @return the value of USER.PASSWORD
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PASSWORD
     *
     * @param password the value for USER.PASSWORD
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.FLAG_ACTIVE
     *
     * @return the value of USER.FLAG_ACTIVE
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public boolean isActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.FLAG_ACTIVE
     *
     * @param active the value for USER.FLAG_ACTIVE
     *
     * @mbggenerated Sun Oct 25 21:19:28 ICT 2015
     */
    public void setActive(boolean active) {
        this.active = active;
    }
}