DROP SCHEMA IF EXISTS TEST_SCHEMA;
DROP TABLE IF EXISTS USERS;

CREATE SCHEMA TEST_SCHEMA AUTHORIZATION SA;

CREATE TABLE USERS(
	ID INT PRIMARY KEY, 
	USER_NAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	FLAG_ACTIVE INT
)