DROP SCHEMA IF EXISTS APP;
DROP TABLE IF EXISTS "USER";

CREATE SCHEMA APP AUTHORIZATION SA;

CREATE TABLE "USER"(
	ID INT PRIMARY KEY, 
	USER_NAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	FLAG_ACTIVE INT
)